version: "3"

services:
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginxapp:/etc/nginx/conf.d
    ports:
      - "80:80"

  app:
    build: ./aspapp
    depends_on:
      - nginx
    # command: sh -c "dotnet WebApplicationTestDocker.dll"
    # volumes:
    #   - ./apsapp/code:/root